version: '3.8'

services:
  airflow:
    build: .
    command: >
      bash -c "airflow db init && airflow webserver & airflow scheduler"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ../crm_app:/opt/crm_app
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@db:5432/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=<YOUR_SECRET_KEY>
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
